email: saiprasad.annamanenidevops369@gmail.com
password: sai369569

disableAntiLock: False

remote: False

experienceLevel:
 internship: False
 entry: False
 associate: False
 mid-senior level: True
 director: False
 executive: False

jobTypes:
 full-time: True
 contract: True
 part-time: False
 temporary: True
 internship: False
 other: False
 volunteer: False

date:
 all time: False
 month: False
 week: True
 24 hours: False

positions:
 - DevOps Consultant
 - Aws DevOps Engineer
 #- ...
locations:
 - Hyderabad
 - Remote
 
industry:
 - Information Technology & Service
 - Software Development
 - Information Services
 - IT Services and IT Consulting
distance: 50

outputFileDirectory: ~/Documents/Applications/EasyApplyBot/EasyApplyBot/

companyBlacklist:
 #- Capgemini
 #- Techmahindra

titleBlacklist:
 #- word1
 #- word2

posterBlacklist:
 #- name1
 #- name2

uploads:
 resume: C:\Users\myDirectory\Resume.pdf
 # Cover letter is optional
 #coverLetter: C:\Users\myDirectory\CoverLettter.pdf


# ------------ QA section -------------------

# ------------ Additional parameters: checkboxes ---------------
checkboxes:
 # Do you have a valid driver's license? (yes/no checkbox)
 driversLicence: False
 # Will you now, or in the future, require sponsorship for employment visa status (e.g. H-1B visa status)? (yes/no checkbox)
 # This is relative to the location and your citizenship applying above, and same with legallyAuthorized.
 requireVisa: False
 # Are you legally authorized to work in COUNTRY? (yes/no checkbox)
 legallyAuthorized: True
 # We must fill this position urgently. Can you start immediately? (yes/no checkbox)
 urgentFill: True
 # Are you comfortable commuting to this job's location? (yes/no checkbox)
 commute: True
 # Are you comfortable working in a remote environment? (yes/no checkbox)
 remote: True
 # Are you comfortable taking a drug in accordance with local/state laws? (yes/no checkbox)
 drugTest: True
 # Are you willing to complete an assessment? (yes/no checkbox)
 assessment: True
 # Have you completed the following level of education: DEGREE TYPE? (yes/no checkbox)
 degreeCompleted:
   - Bachelor's Degree
  # - Doctor of Law
 # Are you willing to undergo a background check, in accordance with local law/regulations?
 backgroundCheck: True

# ------------ Additional parameters: universityGpa ---------------
universityGpa: 0.0

# ------------ Additional parameters: salaryMinimum ---------------
salaryMinimum: 130000

# ------------ Additional parameters: languages ---------------
languages:
 english: Professional # None, Conversational, Professional, Native or bilingual

# ------------ Additional parameters: years of experience ---------------
# How many years of work experience do you have ...? (whole numbers only)
experience:

 AWS: 4
 DevOps: 4
 Terraform: 2
 Kubernetes: 1
 Jenkins: 3
 Docker: 3
 Ansible: 2
 Git: 4
 Github: 4
 Azure: 0
 Php: 0
 Java: 0
 Testing: 0
 #python: 0
 #selenium: 0
 # default to put for any industry/skill that you did not list
 default: 4

# ------------ Additional parameters: personal info ---------------
personalInfo:
 First Name: Sai Prasad
 Last Name: Annamaneni
 Phone Country Code: India (+91) # See linkedin for your country code, must be exact according to the international platform, i.e. Italy (+39) not Italia (+39)
 Mobile Phone Number: 8639188100
 Street address: Dilsukhnagar
 City: Hyderabad # Include the state/province as well!
 State: Telangana
 Zip: 500060
 Linkedin: https://www.linkedin.com/in/sai-prasad-annamaneni-8b5b44249/


# ------------ Additional parameters: USA employment crap ---------------
eeo:
 gender: None
 race: None
 vetran: None
 disability: None
 citizenship: yes
 clearance: no
